# Generated by Django 2.2.9 on 2020-01-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='거래처명')),
                ('tel', models.CharField(max_length=20, verbose_name='거래처전화')),
                ('address', models.CharField(max_length=200, verbose_name='거래처주소')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제품명')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='제품사진')),
                ('desc', models.TextField(verbose_name='제품설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(default=0, verbose_name='남은수량')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Client', verbose_name='거래처')),
            ],
        ),
    ]
